ALTER TABLE facebook_logs
ADD COLUMN IF NOT EXISTS id_new BIGINT GENERATED BY DEFAULT AS IDENTITY;

WITH numbered AS (
  SELECT ctid, row_number() OVER (ORDER BY created_at ASC, ctid) AS rn
  FROM facebook_logs
)
UPDATE facebook_logs f
SET id_new = n.rn
FROM numbered n
WHERE f.ctid = n.ctid
  AND f.id_new IS NULL;

DO $$
DECLARE
  seq_name TEXT;
  max_id BIGINT;
BEGIN
  seq_name := pg_get_serial_sequence('facebook_logs', 'id_new');
  SELECT MAX(id_new) INTO max_id FROM facebook_logs;

  IF seq_name IS NOT NULL THEN
    IF max_id IS NULL THEN
      PERFORM setval(seq_name, 1, false);
    ELSE
      PERFORM setval(seq_name, max_id, true);
    END IF;
  END IF;
END $$;

ALTER TABLE facebook_logs
DROP CONSTRAINT IF EXISTS facebook_logs_pkey;

ALTER TABLE facebook_logs
DROP COLUMN IF EXISTS id;

ALTER TABLE facebook_logs
RENAME COLUMN id_new TO id;

ALTER TABLE facebook_logs
ALTER COLUMN id SET NOT NULL;

ALTER TABLE facebook_logs
ADD PRIMARY KEY (id);
